golang/appengine

internal/main_vm.go

Without this, the Mac OS X firewall asks if _ah_exe should accept
incoming network connections, since by default it listens on all
interfaces. For development purposes, it is sufficient to only listen
on localhost.

main_vm.go: Listen on localhost for dev_appserver; Avoid Mac Firewall

---

internal/api_test.go

There are some major protobuf performance optimizations at work that
improve runtime performance of protobuf, but due to the lack of
batching in the current approach, memory usage will be slightly higher.
This will be eventually fixed.
Adjust the thresholds here to avoid failing the test.
\cc @shantuo @randall77

internal: adjust memory threshold for API test

---

datastore/datastore_test.go
datastore/doc.go
datastore/prop.go
datastore/save.go

The datastore "omitempty" option behaves identically to "omitempty"
in the standard library's encoding/json.
This change is almost identical to https://github.com/GoogleCloudPlatform/google-cloud-go/commit/94f177402d59546c5639e015376f04a6a92b02
Fixes #38

datastore: implement "omitempty" struct field tag option

---

cmd/aebundler/aebundler.go

These are equivalent, but GCR would like to encourage users to switch to
the hyphen form.

Switch google_appengine to google-appengine.

---

datastore/datastore_test.go
datastore/load.go

restructures Load logic to map fields ending in '.' to the anonymous
struct field specified in the codec
Fixes #41

datastore: allow field names ending in '.'

---

aetest/instance.go
aetest/instance_vm.go

In congested test environments it's not uncommon to have 5-30 second
delays. This often results in test flackyness when child startup is
delayed above hardcoded 15 seconds.
This patch allows to pass timeout as an option so it can be configured
specifically for target test environment.

aetest: add StartupTimeout option

---

datastore/prop.go
datastore/prop_test.go

This PR fixes the handling of embedded unexported structs, as discussed in #54.
This functionality existed for years, even predating this package. It was broken due to inaction. Starting from 1.9.35 (March 2016) the Go SDK is based on Go 1.6. The [Go 1.6 release notes](https://golang.org/doc/go1.6#reflect) are explicit in mentioning that packages that use `reflect` need to be updated to keep functional equivalence.

datastore: fix handling of embedded unexported structs

---

cmd/aedeploy/aedeploy.go

The latest version of gcloud builds in the functionality that aedeploy
provided.
This change makes aedeploy a simple wrapper (i.e., $@ in bash) that also
prints deprecation messages.
If you need the previous functionality of aedeploy, then use the v1.0.0
tag.

cmd/aedeploy: deprecate aedeploy

---

README.md

The Flex ("Beta 2") environment does not support many of the App Engine APIs.
Add a section pointing those people toward the upgrade guide on cloud.google.com.
Retain the existing section about aefix, but remove the suggestion that it's useful with the flexible environment.

README: update for flex beta

---

internal/api.go
internal/api_classic.go
internal/api_common.go
internal/identity_classic.go
internal/identity_vm.go
user/user_classic.go

Instead of waiting for a nil return from fromContext to panic, I've
updated all callers to proactively return/panic with a common error
type.  Panic is appropriate here, as it is a failed precondition of
values passed into the functions.  It's not introducing any new panics,
just ones with more useful messages.
Addresses GoogleCloudPlatform/google-cloud-go#523

internal: give more useful panics when (mis)using context.Background

---

user/user_classic.go

This call to ClassicContextFromContext was missed in eda0abe.

user: check for valid context and panic if not

---

.travis.yml

Previously, the travis build would pull from master/HEAD, rather than
from the commit of the pull requests, rendering presubmit tests useless.
Use go_import_path to ensure that HEAD from the pull request is used
instead, and selectively "go get" the other dependencies.

travis: properly test pull requests, rather than always testing tip

---

channel/channel.go

The Channel API feature has been deprecated and is going to be removed.
See the Channel API Turndown document for details and timetable.
https://cloud.google.com/appengine/docs/deprecations/channel

channel: add deprecation message

---

log/log.go

The package docs can be interpreted as: "this package is only for
querying the logs". Unless reader looks at actual func names, it's not
obvious they can actually write the logs as well.
It would be nice to mention this package in any of the tutorials as
well, since stderr output just disappears.

log: clarify package docs

---

delay/delay.go
delay/delay_test.go
taskqueue/taskqueue.go
taskqueue/taskqueue_test.go

This is useful for getting at the request headers (https://cloud.google.com/appengine/docs/standard/go/taskqueue/push/creating-handlers#reading_request_headers)

Make it possible to get taskqueue HTTP headers from inside a delay.Func

---

remote_api/client.go
remote_api/client_test.go

Allows for contexts to be created inside of a request instead of
deriving from a single application-scoped context.
Fixes #86
/cc @shantuo @cybrcodr @stephenmw

remote_api: add long-lived Client type

---

delay/delay.go
delay/delay_go17.go
delay/delay_go17_test.go
delay/delay_pre17.go

Go 1.7 introduced the Context type into the standard library, but it is
assignable to the golang.org/x/net variant.  The appengine libraries are
written in terms of golang.org/x/net, which can interoperate with the
standard library type most of time, but because delay uses reflection,
it depends directly on the exact type.
The test in this change only failed on Go 1.7 and Go 1.8 but not Go
1.9, since after Go 1.9 the golang.org/x/net type became a type alias
for the standard library type.
/cc @cflewis

delay: permit Context from either stdlib or golang.org/x/net

---

aetest/instance_vm.go
appengine.go
internal/api.go
internal/api_classic.go
internal/api_pre17.go

api_pre17.go is a copy of the previous api.go, kept for backwards compatibility.

internal: for Flex, use req.Context instead of a context map

---

datastore/query.go

Fix doc for datastore/query.go.

datastore: fix doc typo in datastore/query.go

---

search/search_test.go

https://cloud.google.com/appengine/docs/standard/go/search/reference#Field
According to the document, Language of Field is "two-letter ISO 639-1 code for the field's language". ISO 639-1 code for Japanese is "ja", not "jp", so I fixed it.
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

search: fix language code of Japanese

---

aetest/instance.go
aetest/instance_vm.go

During testing with the `aetest`'s test instance, some logs generated by underlying dev_appserver appear in outputs.
It's little annoying for reading results of tests.
Therefore, I made a new option parameter to suppress dev_appserver's logs.
How is this?

aetest: Add new option to suppress dev_appserver logs

---

datastore/datastore_test.go
datastore/prop_test.go
datastore/save.go

There are 4 advantages of this change:
1. Saves datastore space (_and cost_).
2. Should slightly decrease write time & write ops (_and costs_) for entities with empty indexed time properties.
3. Avoids noise in the datastore viewer in the form of 0001-01-01 00:00:00 timestamps.
4. Eliminates need to implement `PropertyLoadSaver` to achieve the same.
This change modifies `func isEmptyValue()`. This requires additional type assertion but only for `time.Time` fields with `omitempty` label. Ideally `isEmptyValue()` should be removed completely as it is called just in 1 place inside  `func saveStructProperty()` and it can be a bit optimized. But that would be a too big change and pros are not too big so I believe this can/should be done as a separate PR if desired.
Closes …

datastore: add omitempty support for time.Time - within isEmptyValue() + updated unit tests

---

datastore/query.go
datastore/query_test.go

This adds q.BatchSize() method to avoid the error that claims too many
datastore.next() calls due to the lack of specifying the `count`
property (= batch size).
Fixes #88

datastore: enable to set query batch size

---

internal/transaction.go

#108 made ReadOnly property and previousTransaction argument.
`BeginTransactionRequest.Mode`'s default value is `BeginTransactionRequest_UNKNOWN`.
But `req.PreviousTransaction` required `BeginTransactionRequest_READ_WRITE`.
This test passed before #108 . but after #108 is not.
We get `API error 1 (datastore_v3: BAD_REQUEST): previous_transaction can only be set in READ_WRITE mode` now.
```
// ErrConcurrentTransaction will be occur
err = datastore.RunInTransaction(ctx, func(txCtx1 netcontext.Context) error {
err := datastore.Get(txCtx1, key, &Data{})
if err != nil {
return err
}
err = datastore.RunInTransaction(ctx, func(txCtx2 netcontext.Context) error {
err := datastore.Get(txCtx2, key, &Data{})
if err != nil {
return err
}
_, err = datastore.Put(txCtx2, key, &Data{Str: "#2"})
return err …
```

datastore: fix behavior when ErrConcurrentTransaction occured

---

go.mod
go.sum

github.com/golang/protobuf@v1.2.0 is necessary for the recently updated generated protobuf files in #144.

Update github.com/golang/protobuf to v1.2.0

---

appengine.go
internal/identity.go
internal/identity_classic.go
internal/identity_flex.go

This is motivated by the fact that second-generation runtimes
(>= Go 1.11) do not set the appengine build tag, so the build tag alone
is not sufficient to determine whether an app is running in the standard
environment. We can check for a second-gen runtime with $GAE_ENV.
The new functions centralize this logic so other packages don't have to
worry about the build tags and env vars.
Added:
- IsStandard reports whether the App Engine app is running in the
standard environment. This includes both the first generation
runtimes (<= Go 1.9) and the second generation runtimes (>= Go 1.11).
- IsFlex reports whether the App Engine app is running in the flexible
environment.
- IsAppEngine reports whether the App Engine app is running on App
Engine, in either the standard or flexible environment. …

Add functions that check which environment the app is running in

---

internal/api.go
internal/api_test.go

Fixes #163
The Go 1.11 runtime on GAE Standard is closing the connection before the logs are flushed, which invalidates the security ticket needed to send logs to stackdriver. This can be mitigated by forcing a log flush to happen before the request closes.

Ensure at least one log flush happens before request ends

---

appengine.go
internal/api.go
internal/identity.go

`google.golang.org/appengine/log` mirror every log to stderr.
It is recorded as per-line entries.
I think it is too noisy and useless in second generation runtimes.
This PR switches the behavior depending on whether or not the app is running in the second generation runtimes because the behavior should be saved for `remote_api` users who are using another environments.
refs https://github.com/golang/appengine/issues/176#issuecomment-440568565

log: don't mirror log to stderr on 2nd gen

---

appengine.go
delay/delay.go
delay/delay_test.go
internal/main.go
internal/main_common.go
internal/main_test.go
internal/main_vm.go

Add support for stable Func keys in App Engine second gen

---

internal/api.go

This adds support for RunInBackground by ensuring that the request ID is correctly associated with the request. Does not fix the issue in prod for `runtime: go111`, which is a separate internal change landing soon.

internal: Respect X-Appengine-Dev-Request-Id header

---

appengine.go

internal.Call is exposed by the APICall method.

Remove TODO that has been implemented.

---

README.md

The correct path for the App Engine start handler is /_ah/start.

Change /_ah/startup to /_ah/start in README

---

capability/capability.go

The capabilities API was deprecated to only return status for "datastore_v3" and "write", and return ENABLED for everything else. This removes unnecessary RPC calls from the client-side.

Simplify the capabilities API to remove unnecessary RPC calls

---

internal/net.go

Increase `internal.limitDial`'s timeout from 500ms to 10s, to account for differences in the go111 legacy API endpoint.

internal: Increase limitDial timeout from 500ms to 10s

---

delay/delay.go
delay/delay_test.go

The path for the files does not contain an underscore anymore, removing it works with the current and the old behavior.
Also if the delay function is defined globally, the internal.MainPath is not available yet. I removed the ` internal.MainPath == ""` check because it was only there for the test and refactored the test a little bit to make it work.

delay: fix stable func name to strip gopath prefix

---

aetest/instance_vm.go

The aetest displays an error in the new version of App Engine Go Extensions.
I created a pull request because I was able to continue using aetest by setting the runtime to go111.
Before:
```console
$ go test
INFO     2019-10-04 13:15:01,475 devappserver2.py:224] Using Cloud Datastore Emulator.
We are gradually rolling out the emulator as the default datastore implementation of dev_appserver.
If broken, you can temporarily disable it by --support_datastore_emulator=False
Read the documentation: https://cloud.google.com/appengine/docs/standard/python/tools/migrate-cloud-datastore-emulator
Help us validate that the feature is ready by taking this survey: https://goo.gl/forms/UArIcs8K9CUSCm733
Report issues at: https://issuetracker.google.com/issues/new?component=187272
INFO     2019-10-04 …
```

aetest: appYAMLTemplate should use runtime: go111

---

.travis.yml
aetest/instance_classic.go
appengine.go
cloudsql/cloudsql_classic.go
internal/api_classic.go
internal/identity.go
internal/identity_classic.go
internal/main.go
socket/socket_classic.go
travis_install.sh
travis_test.sh
user/user_classic.go

Reverts golang/appengine#217 -- breaks tests downstream. Will reland once we've migrated those affected (likely O(weeks) time)

Revert "Remove support for 1.10 and earlier"

---

internal/api.go

Since these calls are all made to the same host, persisting connections
and specifying the timeouts yields performance and throughput improvements.

[internal] Optimize HTTP transport params

---

.travis.yml
aetest/user.go
internal/api_test.go

The `aetest` package sets the wrong `Federated-Identity` headers, so tests which relied on them fail when moved to the new environment.

[aetest] Fix Federated-Identity headers

---

aetest/instance_vm.go

by setting the environment variable "APPENGINE_DEV_APPSERVER_BINARY" to the path of an executable file, `aetest` will now use it to launch the devappserver.

[aetest] Allow specifying path to dev_appserver binary

---

internal/api.go
internal/api_test.go

Set LOG_TO_LOGSERVICE=0 to prevent sending logs to logservice.  The longer term goal is to remove all of the code behind this flag and replace with structured json logs.  The gen2 runtimes watch /var/log for structured logfiles and forwards their records to stackdriver.

add flag to disable logservice

---

aetest/instance_vm.go

If the environment variable `APPENGINE_DEV_APPSERVER_DATASTORE_PATH` is set, use it as the path to the dev_appserver datastore file, rather than the default of `filepath.Join(i.appDir, "datastore")`

[atest] Specify path to dev_appserver datastore file via APPENGINE_DEV_APPSERVER_DATASTORE_PATH

---

.github/workflows/ci-v2.yaml
CONTRIBUTING.md
v2/CONTRIBUTING.md
v2/cmd/aefix/ae.go
v2/cmd/aefix/fix.go

* Enable aetest tests
* Fix v2/aefix to work with appengine/v2

Run ci workflow on v2

---

v2/internal/api.go

For consistency with go's std logging package, work being done in the Python and Java GAE runtimes, and general posix conventions.

switch default logStream from stdout to stderr

---

v2/internal/log.go
v2/internal/log_test.go

Thanks for releasing v2.
I tried the log API on GAE 2nd gen, but it didn't associate with the request log.
The request header to get a trace id and a span id is correct `X-Cloud-Trace-Context`, not `Cloud-Trace-Context`.

Fix header name to associate log entry & trace

---

.github/workflows/ci-v2.yaml
.github/workflows/ci.yml
README.md
v2/internal/api.go
v2/internal/log.go
v2/internal/log_test.go

- Pin setup-gcloud gh action to v0 instead of head
- Typo fix
- qa changes equivalent of changes to master
- https://github.com/golang/appengine/pull/272
- https://github.com/golang/appengine/pull/255
- https://github.com/golang/appengine/pull/263

refactor: pin setup-gcloud gh action to v0

---

.github/workflows/ci-v2.yaml
.github/workflows/ci.yml

With google-github-actions/setup-gcloud#539, they broke Github workflows specifying the "master" branch ahead of the rename of the branch to 'main'.

Fix golang/appengine CI

---

v2/aetest/instance.go

See #232 for rationale.
This change slipped through the cracks because it was added to v1 after v2 was forked, but before v2 was landed.

re-apply PR #232 to v2

---

v2/appengine.go
v2/internal/api.go
v2/internal/api_test.go
v2/internal/main.go

See #235 for rationale.
This change slipped through the cracks because it was added to v1 after v2 was forked, but before v2 was landed.

re-apply PR #235 to v2

---

.github/workflows/ci-v2.yaml
.github/workflows/ci.yml

Python2 has to be installed manually now on a latest Ubuntu image in order to be used by devappserver tests.
Also extended tests for Go 1.20 and remove a unsupported go 1.11 test.
Wit these changes all github testsactions are green.

Install Python2 in base image for DevAppServer tests and change test matrix for 1.11 and 1.20.x

---

v2/internal/api.go
v2/internal/api_test.go
v2/internal/net_test.go

This makes the test more hermetic by avoiding the need to set env vars, and it also avoids some unecessary duplication of test helper logic by leveraging some of aetest's underlying implementation (namely RegisterTestRequest).
This change was originally part of #284, but I split it out because it's not compatible with v1's log flushing tests, and it would have added unecessary noise to that PR.

just a small refactor of api_test

---

.github/workflows/ci-update-workflow.yml

Fix the ci-update-workflow GitHub Actions:
1. Add `workflow_dispatch` to allow manually trigger the GitHub Actions.
2. Configure permissions for the `GITHUB_TOKEN` to be able to create the pull request - currently it's failing with an error https://github.com/golang/appengine/actions/runs/4509959366/jobs/7940335103

Fix the ci-update-workflow GitHub Actions

---

.github/workflows/ci-v2.yaml
.github/workflows/ci.yml
aetest/instance_vm.go
v2/aetest/instance.go

Update .github/workflows/ci.yml to use python3 instead of python 2.7 when calling gcloud.

Upgrade python version being used by the ci workflow.

---

internal/api_test.go
v2/internal/api_test.go

A sample timeout error can be found at https://github.com/golang/appengine/actions/runs/5524135326/jobs/10076013873.

Extend the deadline of a test context to fix a timeout issue.

---

.github/workflows/ci-v2.yaml

- go-version matrix updates
Update the go-version matrix in the CI workflows to include the new supported runtimes.
Auto-generated by https://github.com/chizhg/serverless-runtimes-automation/actions/runs/5901438099

[Automation] Update go-version matrix

---

.github/dependabot.yml
.github/workflows/ci-update-workflow.yml

Closes #331
Implemented as described on the issue, but also specified dependabot configuration for GO modules.
The suggested configuration is set up to:
- Update github actions together in a single monthly PR
- Version updates for GO modules from "/go.mod" will be sent together in a weekly PR.
- Version updates for GO modules from "/v2/go.mod" will be sent separately from the
ones in "/go.mod", but will also be sent together in a weekly PR.
Let me know if you'd rather have a different setting.
Cheers,

Feature: Hash-pin sensitive workflow dependencies and enable dependabot for them

---

.github/workflows/ci-v2.yaml
.github/workflows/ci.yml
aetest/instance_vm.go
v2/aetest/instance.go

Should address https://github.com/golang/appengine/issues/350.

Update go versions to 1.22
